---
 - name: variables
   hosts: local
   connection: local
   vars:
    course: ansible
    duration: 11HR
    Trainer: satyam

    tasks:
    - name: print course information
      ansible.builtin.debug:
      msg: "HELLO {{ COURSE }} duration {{ DURATION }} trainer name {{ TRAINER }}"

