---
 - name: variables
   hosts: 98.83.157.28
   connection: 98.83.157.28
   vars:
      course: Devops with AWS
      duration: 11HR
      trainer: satyam

   tasks: 
    - name: print course information
      vars:
        course: Ansible 
      ansible.builtin.debug:
         msg: "Hello {{ course }}  {{ duration }} {{ trainer }}"



 
    