---
 - name: variables
   hosts: local
   connection: local
   vars:
    course: Devops with AWS
    duration: 11HR
    trainer: satyam


   tasks: 
   - name: print course information 
     vars: 
     course: ansible
     ansible.builtin.debug:
       msg: "HELLO {{ course }} duration {{ duration }} trainer name {{ trianer }}"
       
